feat: create match and add validation
sedelinggam/cats-social pull request #16
Opened 2024-05-01 06:46 UTC by shevaathalla

### Progress
- create match migrations
- create match service n repo
- add validation
![image](https://github.com/sedelinggam/cats-social/assets/33413409/461a4daf-ddad-4459-aec0-ef527f52a94f)

### Todo
- add transaction on service
- add update mechanism on cat that already matched

2024-05-01 11:46 UTC, abdmmar requested changes
Commented, sama boleh tolong attach postman collection-nya di deskripsi? thanks

2024-05-01 11:46 UTC, abdmmar commented on internal/delivery/http/v1/controller/matches/matches_controller.go
> +	user := group.Group("/cat/match")
```suggestion
	match := group.Group("/cat/match")
```

2024-05-01 11:46 UTC, abdmmar commented on internal/delivery/http/v1/request/matches_request.go
> +	Message    string `json:"message" validate:"required"`
Ini udah pake `validate` cuman kayaknya belum pake `validator` di `create_match_handler`-nya ya? sama kayaknya bisa tambahin validasi `min` sama `max` char:

```suggestion
	Message    string `json:"message" validate:"required,min=5,max=120"`
```

2024-05-01 11:46 UTC, abdmmar commented on internal/delivery/http/v1/controller/matches/handler/create_match_handler.go
> +
Kyknya bisa ditambahin validasi disini:
```suggestion
// Create a new validator instance
	validate := validator.New()

	// Validate the Create Match struct
	err = validate.Struct(req)
	if err != nil {
		// Validation failed, handle the error
		return lumen.FromError(lumen.NewError(lumen.ErrBadRequest, err)).SendResponse(c)
	}
```

2024-05-01 15:15 UTC, malikilamalik commented on internal/delivery/http/v1/controller/matches/handler/create_match_handler.go
> +		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
Error handlingnya pak.
```suggestion
		return lumen.FromError(err).SendResponse(c)
```

2024-05-01 15:21 UTC, shevaathalla commented on internal/delivery/http/v1/request/matches_request.go
> +	Message    string `json:"message" validate:"required"`
adjusted mas thanks

2024-05-01 15:22 UTC, shevaathalla commented on internal/delivery/http/v1/controller/matches/handler/create_match_handler.go
> +		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
adjusted mas

2024-05-01 15:51 UTC, abdmmar approved these changes

2024-05-01 16:15 UTC, malikilamalik approved these changes

2024-05-01 17:10 UTC, abdmmar commented
eh @shevaathalla merge-nya ke `main` branch ya

2024-05-02 06:24 UTC, shevaathalla commented
> eh @shevaathalla merge-nya ke `main` branch ya

adjusted

2024-05-02 14:19 UTC, achmadmuzaki14 approved these changes

2024-05-02 14:53 UTC, merged